/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 linkedin.gltf --transform 
Files: linkedin.gltf [152.96KB] > linkedin-transformed.glb [20.81KB] (86%)
Author: studiometa (https://sketchfab.com/studiometa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/linkedin-3d-c62b9be6edfc46b4a887c2a2ff0148d8
Title: Linkedin 3D
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Linkedin(props) {
  const { nodes, materials } = useGLTF('./linkedin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Objeto_1_Tinta_(1)_0'].geometry} material={materials.Tinta_1} scale={0.005} />
      <mesh geometry={nodes['Objeto_2_Tinta_(3)_0'].geometry} material={materials.Tinta_3} scale={0.005} />
    </group>
  )
}

useGLTF.preload('./linkedin-transformed.glb')
